print("Hello world🥰🤗")
print("This is my first program in Python")
print("I am learning Python programming language")
print("I am enjoying it very much")
print("I will become a Python developer soon")
print("Hi, I am Alpha coder😎🤗")
print(4)
print(0.6)
print("I am 17 year old ")
print("I am 17 year old ")
print("I ❤ python")
print("I am learning python programming language")
print("Stay happy and stay healthy🩺")